-- INITIALIZE HOURS
-- 코드를 입력하세요
WITH RECURSIVE
cte (HOUR) AS
(
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 FROM cte WHERE HOUR < 23
)
SELECT
    HOUR, 
    COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM cte
LEFT JOIN ANIMAL_OUTS 
    ON HOUR = HOUR(DATETIME)
GROUP BY HOUR;